"""
Django settings for notastudiosapi project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
#--Neon--
import os
from dotenv import load_dotenv
from urllib.parse import urlparse, parse_qsl
#--Neon end--

from pathlib import Path
from django.core.management.utils import get_random_secret_key

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

#--Neon--
load_dotenv(BASE_DIR.parent / ".env.backend")
#--Neon end--

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# vars
# Used when the backend/Dockerfile is built; manage.py functions require settings.py to be available
IS_BUILDING_DOCKER_IMAGE =os.getenv("DJANGO_BUILD", "").lower() == "true"


# SECURITY WARNING: keep the secret key used in production secret!
# Random secret key is used during Docker build, else use the secret key in .env.backend
SECRET_KEY = os.getenv("SECRET_KEY", default=get_random_secret_key())


# SECURITY WARNING: don't run with debug turned on in production!
# Modify the DEBUG field in .env.backend. Use 'True' for local dev.
DEBUG = os.getenv("DEBUG", "False").lower() == "true"


#Get Allowed Hosts from env
hosts = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1")

hosts = hosts.split(",")
allowed_hosts = []

for host in hosts:
    host = host.strip()

    if host:
        allowed_hosts.append(host)

ALLOWED_HOSTS = allowed_hosts


# Get CORS Allowed Origins from environment
cors_origins_value = os.getenv("CORS_ALLOWED_ORIGINS","")

CORS_ALLOWED_ORIGINS = []

for origin in cors_origins_value.split(","):
    cleaned_origin = origin.strip()

    if cleaned_origin:
        CORS_ALLOWED_ORIGINS.append(cleaned_origin)


# Application definition
INSTALLED_APPS = [
    #Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    "corsheaders",
    "storages",

    # Local
    "appapi.apps.AppAPIConfig",
]


aws_bucket_name = 'notastudios-s3-bucket'
aws_region_name = 'us-east-2'


STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "bucket_name": aws_bucket_name,
            "region_name": aws_region_name,
            "location": "media",
            "default_acl": None,
            "file_overwrite": False,
            "querystring_auth": True,
            "signature_version": "s3v4",
        },
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'notastudiosapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'notastudiosapi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
if IS_BUILDING_DOCKER_IMAGE:
    # Use SQL Lite as default when running Docker build
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db-backup.sqlite3',
        }
    }
else:
    # Set DATABASE_URL in .env
    database_url = os.getenv("DATABASE_URL")

    if not database_url:
        raise RuntimeError("DATABASE_URL is not configured. Add it to backend/.env.backend")


    postgres = urlparse(database_url)

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            "NAME": postgres.path.lstrip("/"),
            'USER': postgres.username,
            'PASSWORD': postgres.password,
            'HOST': postgres.hostname,
            "PORT": postgres.port or 5432,
            'OPTIONS': dict(parse_qsl(postgres.query)),
        },
        'sqlite': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db-backup.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL ='/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

