"""
Django settings for notastudiosapi project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
#--Neon--
import os
from dotenv import load_dotenv
from urllib.parse import urlparse, parse_qsl
#--Neon end--

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

#--Neon--
load_dotenv(BASE_DIR.parent / ".env.backend")
#--Neon end--

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

if not SECRET_KEY:
    raise RuntimeError("SECRET_KEY is not configured. Add it to backend/.env.backend")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() == "true"


#Get Allowed Hosts from env
hosts = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1")

hosts = hosts.split(",")
allowed_hosts = []

for host in hosts:
    host = host.strip()

    if host:
        allowed_hosts.append(host)

ALLOWED_HOSTS = allowed_hosts


# Get CORS Allowed Origins from environment
cors_origins_value = os.getenv(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:3000"
)

CORS_ALLOWED_ORIGINS = []

for origin in cors_origins_value.split(","):
    cleaned_origin = origin.strip()

    if cleaned_origin:
        CORS_ALLOWED_ORIGINS.append(cleaned_origin)


# Application definition
INSTALLED_APPS = [
    #Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    "corsheaders",
    "storages",

    # Local
    "appapi.apps.AppAPIConfig",
]


aws_bucket_name = os.getenv("AWS_STORAGE_BUCKET_NAME")
aws_region_name = os.getenv("AWS_S3_REGION_NAME")

if not aws_bucket_name:
    raise RuntimeError("AWS_STORAGE_BUCKET_NAME is not configured. Add it in backend/.env")


if not aws_region_name:
    raise RuntimeError("AWS_S3_REGION_NAME is not configured. Add it in backend/.env")


STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "bucket_name": aws_bucket_name,
            "region_name": aws_region_name,
            "location": "media",
            "default_acl": None,
            "file_overwrite": False,
            "querystring_auth": True,
            "signature_version": "s3v4",
        },
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'notastudiosapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'notastudiosapi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Replace the DATABASES section of your settings.py with this
database_url = os.getenv("DATABASE_URL")

if not database_url:
    raise RuntimeError("DATABASE_URL is not configured. Add it to backend/.env.backend")


postgres = urlparse(database_url)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        "NAME": postgres.path.lstrip("/"),
        'USER': postgres.username,
        'PASSWORD': postgres.password,
        'HOST': postgres.hostname,
        "PORT": postgres.port or 5432,
        'OPTIONS': dict(parse_qsl(postgres.query)),
    },
    'sqlite': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db-backup.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

