# Generated by Django 6.0.6 on 2026-07-07 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSchedule',
            fields=[
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3, primary_key=True, serialize=False)),
                ('start_time', models.TimeField(verbose_name='time open')),
                ('end_time', models.TimeField(verbose_name='time closed')),
            ],
        ),
        migrations.DeleteModel(
            name='ServiceHours',
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='studioequipment',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
