# Generated by Django 6.0.6 on 2026-07-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0002_serviceschedule_delete_servicehours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceschedule',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=3, primary_key=True, serialize=False),
        ),
    ]
