# Generated by Django 6.0.6 on 2026-07-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0004_alter_serviceschedule_day_of_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=100)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='imgs/artists/')),
                ('featured_image_alt', models.CharField(blank=True, max_length=100)),
                ('artist_bio', models.CharField(max_length=255)),
                ('social_link', models.CharField(max_length=255)),
            ],
        ),
    ]
