# Generated by Django 6.0.6 on 2026-07-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0005_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.AddField(
            model_name='service',
            name='priceDesc',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_bio',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='service',
            name='sub_description',
            field=models.CharField(max_length=500),
        ),
    ]
