# Generated by Django 6.0.6 on 2026-07-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0006_remove_service_price_service_pricedesc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='sub_description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
