# Generated by Django 6.0.6 on 2026-07-14 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0007_alter_service_sub_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='priceDesc',
            new_name='price_desc',
        ),
    ]
