# Generated by Django 6.0.6 on 2026-07-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0008_rename_pricedesc_service_price_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_bio',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='artist',
            name='featured_image_alt',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_desc',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='sub_description',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='studioequipment',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
