# Generated by Django 6.0.6 on 2026-07-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0009_alter_artist_artist_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('audio_file', models.FileField(upload_to='audio/music/')),
                ('album_art', models.ImageField(blank=True, null=True, upload_to='audio/artwork/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
