# Generated by Django 6.0.6 on 2026-07-24 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0010_music'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Music',
            new_name='Track',
        ),
    ]
