# Generated by Django 6.0.6 on 2026-07-24 17:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0012_track_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
