# Generated by Django 6.0.6 on 2026-07-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0015_alter_track_audio_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['-release_date']},
        ),
        migrations.AlterField(
            model_name='track',
            name='description',
            field=models.TextField(blank=True, default='Recorded, Mixed & Mastered - NOTA Studios, Pittsburgh, PA', max_length=500, null=True),
        ),
    ]
