# Generated by Django 6.0.6 on 2026-07-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0016_alter_track_options_alter_track_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Leave blank to generate automatically from title.', unique=True)),
                ('sub_title', models.CharField(blank=True, max_length=255)),
                ('author', models.CharField(max_length=50)),
                ('content', models.TextField(help_text='Full blog post using Markdown')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_desc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='sub_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='studioequipment',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='description',
            field=models.TextField(blank=True, default='Recorded, Mixed & Mastered - NOTA Studios, Pittsburgh, PA', null=True),
        ),
    ]
