# Generated by Django 6.0.6 on 2026-07-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0017_blogpost_alter_artist_artist_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
