# Generated by Django 6.0.6 on 2026-07-27 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0019_alter_track_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='artist_relation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tracks', to='appapi.artist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
