# Generated by Django 6.0.6 on 2026-07-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0020_track_artist_relation_alter_track_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
