# Generated by Django 6.0.6 on 2026-07-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0021_alter_track_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='artist',
        ),
        migrations.AddField(
            model_name='artist',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
