# Generated by Django 6.0.6 on 2026-07-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0022_remove_track_artist_artist_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='social_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
