# Generated by Django 6.0.6 on 2026-07-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0023_alter_artist_social_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='artist_relation',
            new_name='artist',
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_bio',
            field=models.TextField(blank=True),
        ),
    ]
